### ISSUE TITLE
Functional Prototype Roadmap

### ISSUE THREAD

**Issue by ducdetronquito** [ducdetronquito/fire#1]
## Done
- [x] Display a map with buildings
- [x] Handle map relief
- [x] Handle map cell selection
- [x] Can add torches on a cell with a building
- [x] Selection and destruction of a non-illuminated building
- [x] Increasing of a faction's fear gauge on a building destruction

### Gameplay
- [] Handle turn-based system (with timer ?) and passed nights counter.
- [] Decide how to decrease faction's fear gauge during the game

### Graphics
- [] Decide how to do visual transition from day to night, and night to day
- [] Decide how to have dynamic illumination of buildings with shadows.
